'use client';
import { useCallback,useEffect,useState } from 'react';
import Link from 'next/link';
import { csrfFetch } from '@/lib/csrf-client';
import PublicPollResults from '@/components/PublicPollResults';
import type { pollView,publicPollResults } from '@/lib/public-polls';
type Poll=ReturnType<typeof pollView>&{counts:{ballots:number;confirmed:number};results:ReturnType<typeof publicPollResults>|null};
export default function PublicPollManager() {
  const [editing,setEditing]=useState<string|null>(null),[security,setSecurity]=useState<Record<string,Array<{ip:string;submissions:number;distinctEmails:number;first:number;last:number}>>>({});
  const [polls,setPolls]=useState<Poll[]>([]),[showForm,setShowForm]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[question,setQuestion]=useState('Who would you prefer?'),[options,setOptions]=useState(''),[opens,setOpens]=useState(''),[closes,setCloses]=useState(''),[confirms,setConfirms]=useState('');
  const load=useCallback(async()=>{const r=await fetch('/api/admin/public-polls',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setPolls(d.polls);},[]);
  useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
  async function action(body:any,prompt?:string) {if(prompt&&!window.confirm(prompt))return;setBusy(true);setError('');setMessage('');try{const r=await csrfFetch('/api/admin/public-polls',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setMessage(body.action==='create'?'Draft created. Review it below before opening.':'Poll updated.');if(['create','update'].includes(body.action)){setShowForm(false);setEditing(null);}}catch(e:any){setError(e.message||'Unable to save.');}finally{setBusy(false);}}
  return <div className="mx-auto max-w-5xl p-4 sm:p-6 space-y-6"><div className="flex flex-wrap justify-between gap-4"><h1 className="text-3xl font-bold">Public polls</h1><button className="btn-primary" onClick={()=>{setShowForm(!showForm);setEditing(null);}}>{showForm?'Cancel':'Create public poll'}</button></div>
    <p>Anyone with the link can participate. No invitation or electoral roll is required. Email confirmation is separate from membership and identity verification.</p>
    {error&&<p role="alert" className="rounded bg-red-50 border border-red-200 p-4">{error}</p>}{message&&<p role="status" className="rounded bg-green-50 p-4">{message}</p>}
    {showForm&&<form className="card p-5 space-y-4" onSubmit={e=>{e.preventDefault();action({action:editing?'update':'create',id:editing,title,description,question,options:options.split('\n').map(x=>x.trim()).filter(Boolean),opens_at:new Date(opens).getTime(),closes_at:new Date(closes).getTime(),confirms_until:new Date(confirms).getTime()});}}>
      <h2 className="text-xl font-bold">{editing?'Edit public poll draft':'New public poll'}</h2><p className="text-sm">This first version has one optional-preference ranking question, a Greens membership question and email confirmation. Counts use Condorcet with Schulze fallback.</p>
      <label className="block font-medium">Title<input required maxLength={200} className="input-field mt-1" value={title} onChange={e=>setTitle(e.target.value)}/></label>
      <label className="block font-medium">Introduction<textarea required maxLength={10000} rows={4} className="input-field mt-1" value={description} onChange={e=>setDescription(e.target.value)}/></label>
      <label className="block font-medium">Ranking question<input required maxLength={500} className="input-field mt-1" value={question} onChange={e=>setQuestion(e.target.value)}/></label>
      <label className="block font-medium">Options, one per line<textarea required rows={8} className="input-field mt-1" value={options} onChange={e=>setOptions(e.target.value)}/></label>
      <p className="text-sm text-gray-600">Dates use your browser’s local timezone. Confirmation can remain open for up to 48 hours after submissions close. Options and dates are fixed once the poll is opened; review carefully.</p>
      <div className="grid gap-4 md:grid-cols-3">{[['Opens',opens,setOpens],['Submissions close',closes,setCloses],['Confirmation closes',confirms,setConfirms]].map(([label,value,set])=><label key={label as string} className="block font-medium min-w-0">{label as string}<input required type="datetime-local" className="input-field mt-1 min-w-0" value={value as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}</div>
      <p className="text-sm">Email/IP/time records are encrypted separately from ballots. Finalisation removes their link to rankings. This is not operator-proof anonymity while confirmation is open.</p><button className="btn-primary" disabled={busy}>{editing?'Save draft':'Create draft for review'}</button>
    </form>}
    {!polls.length&&!showForm&&<p className="py-8 text-gray-600">No public polls yet.</p>}
    {polls.map(p=><article key={p.id} className="card p-5 space-y-4"><div className="flex justify-between gap-4"><h2 className="text-xl font-bold break-words">{p.title}</h2><span className="text-sm font-medium">{p.status==='open'&&Date.now()>=p.closes_at?'Submissions closed':p.status}</span></div><p className="whitespace-pre-wrap break-words">{p.description}</p>
      <p className="text-sm">Opens: {new Date(p.opens_at).toLocaleString()}<br/>Submissions close: {new Date(p.closes_at).toLocaleString()}<br/>Confirmation closes: {new Date(p.confirms_until).toLocaleString()}</p>
      <details><summary className="cursor-pointer">Review question and options</summary><p className="font-semibold mt-3">{p.question}</p><ul className="list-disc pl-5">{p.options.map(x=><li key={x}>{x}</li>)}</ul></details>
      <p>{p.counts.ballots} accepted ballots · {p.counts.confirmed} email-confirmed</p>
      {p.status==='draft'&&<div className="flex flex-wrap gap-3"><button disabled={busy} className="btn-secondary" onClick={()=>{setEditing(p.id);setTitle(p.title);setDescription(p.description);setQuestion(p.question);setOptions(p.options.join('\n'));const local=(n:number)=>{const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};setOpens(local(p.opens_at));setCloses(local(p.closes_at));setConfirms(local(p.confirms_until));setShowForm(true);window.scrollTo({top:0,behavior:'smooth'});}}>Edit draft</button><button disabled={busy} className="btn-secondary" onClick={()=>action({action:'delete',id:p.id},'Permanently delete this unpublished draft?')}>Delete draft</button></div>}
      {p.status==='open'&&<details><summary className="cursor-pointer" onClick={()=>{fetch('/api/admin/public-polls?security='+p.id,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setSecurity(s=>({...s,[p.id]:d.security}));}).catch(e=>setError(e.message));}}>Restricted abuse review</summary><p className="text-sm my-3">Shared IP addresses are not proof of duplicate people. These network-level totals do not disclose rankings or email addresses and disappear at finalisation.</p><ul className="space-y-2 text-sm break-words">{security[p.id]?.map(g=><li key={g.ip}>{g.ip}: {g.submissions} submissions across {g.distinctEmails} email addresses. First {new Date(g.first).toLocaleString()}; last {new Date(g.last).toLocaleString()}.</li>)}</ul></details>}
      <div className="flex flex-wrap gap-3">{p.status==='draft'?<button disabled={busy} className="btn-primary" onClick={()=>action({action:'open',id:p.id},'Open this public poll? Anyone with its link can submit during the voting window. Check every option and deadline first.')}>Open public poll</button>:<Link className="btn-secondary" href={`/poll/${p.id}`}>View public link</Link>}
      {['open','sealing'].includes(p.status)&&<button disabled={busy||Date.now()<p.confirms_until} className="btn-secondary" onClick={()=>action({action:'finalise',id:p.id},'Finalise and de-identify? This permanently removes verification links and prevents any further confirmations. Results stay private until you publish them.')}>{p.status==='sealing'?'Retry privacy finalisation':'Finalise and de-identify'}</button>}
      {p.status==='finalised'&&<button disabled={busy} className="btn-primary" onClick={()=>action({action:'publish_results',id:p.id},'Publish aggregate results to everyone with the poll link?')}>Publish results</button>}</div>
      {p.results&&<PublicPollResults results={p.results} options={p.options}/>}
    </article>)}
  </div>;
}
